/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: mt5api.i

#ifndef SWIG_mt5api_WRAP_H_
#define SWIG_mt5api_WRAP_H_

class Swig_memory;

class SwigDirector_IMTTickSink : public IMTTickSink
{
 public:
  SwigDirector_IMTTickSink(int swig_p);
  void _swig_upcall_OnTickShort(LPCWSTR arg0,MTTickShort const &arg1) {
    IMTTickSink::OnTick(arg0,arg1);
  }
  virtual void OnTick(LPCWSTR arg0,MTTickShort const &arg1);
  void _swig_upcall_OnTickStatShort(MTTickStat const &arg0) {
    IMTTickSink::OnTickStat(arg0);
  }
  virtual void OnTickStat(MTTickStat const &arg0);
  MTAPIRES _swig_upcall_HookTick(int const arg0,MTTick &arg1) {
    return IMTTickSink::HookTick(arg0,arg1);
  }
  virtual MTAPIRES HookTick(int const arg0,MTTick &arg1);
  MTAPIRES _swig_upcall_HookTickStat(int const arg0,MTTickStat &arg1) {
    return IMTTickSink::HookTickStat(arg0,arg1);
  }
  virtual MTAPIRES HookTickStat(int const arg0,MTTickStat &arg1);
  void _swig_upcall_OnTickServer(int const arg0,MTTick const &arg1) {
    IMTTickSink::OnTick(arg0,arg1);
  }
  virtual void OnTick(int const arg0,MTTick const &arg1);
  void _swig_upcall_OnTickStatServer(int const arg0,MTTickStat const &arg1) {
    IMTTickSink::OnTickStat(arg0,arg1);
  }
  virtual void OnTickStat(int const arg0,MTTickStat const &arg1);
 private:
  intgo go_val;
  Swig_memory *swig_mem;
};

class SwigDirector_IMTPositionSink : public IMTPositionSink
{
 public:
  SwigDirector_IMTPositionSink(int swig_p);
  void _swig_upcall_OnPositionAdd(IMTPosition const *arg0) {
    IMTPositionSink::OnPositionAdd(arg0);
  }
  virtual void OnPositionAdd(IMTPosition const *arg0);
  void _swig_upcall_OnPositionUpdate(IMTPosition const *arg0) {
    IMTPositionSink::OnPositionUpdate(arg0);
  }
  virtual void OnPositionUpdate(IMTPosition const *arg0);
  void _swig_upcall_OnPositionDelete(IMTPosition const *arg0) {
    IMTPositionSink::OnPositionDelete(arg0);
  }
  virtual void OnPositionDelete(IMTPosition const *arg0);
  void _swig_upcall_OnPositionClean(UINT64 const arg0) {
    IMTPositionSink::OnPositionClean(arg0);
  }
  virtual void OnPositionClean(UINT64 const arg0);
  void _swig_upcall_OnPositionSync() {
    IMTPositionSink::OnPositionSync();
  }
  virtual void OnPositionSync();
 private:
  intgo go_val;
  Swig_memory *swig_mem;
};

class SwigDirector_IMTDealSink : public IMTDealSink
{
 public:
  SwigDirector_IMTDealSink(int swig_p);
  void _swig_upcall_OnDealAdd(IMTDeal const *arg0) {
    IMTDealSink::OnDealAdd(arg0);
  }
  virtual void OnDealAdd(IMTDeal const *arg0);
  void _swig_upcall_OnDealUpdate(IMTDeal const *arg0) {
    IMTDealSink::OnDealUpdate(arg0);
  }
  virtual void OnDealUpdate(IMTDeal const *arg0);
  void _swig_upcall_OnDealDelete(IMTDeal const *arg0) {
    IMTDealSink::OnDealDelete(arg0);
  }
  virtual void OnDealDelete(IMTDeal const *arg0);
  void _swig_upcall_OnDealClean(UINT64 const arg0) {
    IMTDealSink::OnDealClean(arg0);
  }
  virtual void OnDealClean(UINT64 const arg0);
  void _swig_upcall_OnDealSync() {
    IMTDealSink::OnDealSync();
  }
  virtual void OnDealSync();
  void _swig_upcall_OnDealPerform(IMTDeal const *arg0,IMTAccount *arg1,IMTPosition *arg2) {
    IMTDealSink::OnDealPerform(arg0,arg1,arg2);
  }
  virtual void OnDealPerform(IMTDeal const *arg0,IMTAccount *arg1,IMTPosition *arg2);
  void _swig_upcall_OnDealPerformCloseBy(IMTDeal const *arg0,IMTDeal const *arg1,IMTAccount *arg2,IMTPosition *arg3) {
    IMTDealSink::OnDealPerformCloseBy(arg0,arg1,arg2,arg3);
  }
  virtual void OnDealPerformCloseBy(IMTDeal const *arg0,IMTDeal const *arg1,IMTAccount *arg2,IMTPosition *arg3);
 private:
  intgo go_val;
  Swig_memory *swig_mem;
};

#endif
