/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: mt5api.i

#ifndef SWIG_mt5api_WRAP_H_
#define SWIG_mt5api_WRAP_H_

class Swig_memory;

class SwigDirector_IMTTickSink : public IMTTickSink
{
 public:
  SwigDirector_IMTTickSink(int swig_p);
  void _swig_upcall_OnTickShort(LPCWSTR arg0,MTTickShort const &arg1) {
    IMTTickSink::OnTick(arg0,arg1);
  }
  virtual void OnTick(LPCWSTR arg0,MTTickShort const &arg1);
  void _swig_upcall_OnTickStatShort(MTTickStat const &arg0) {
    IMTTickSink::OnTickStat(arg0);
  }
  virtual void OnTickStat(MTTickStat const &arg0);
  MTAPIRES _swig_upcall_HookTick(int const arg0,MTTick &arg1) {
    return IMTTickSink::HookTick(arg0,arg1);
  }
  virtual MTAPIRES HookTick(int const arg0,MTTick &arg1);
  MTAPIRES _swig_upcall_HookTickStat(int const arg0,MTTickStat &arg1) {
    return IMTTickSink::HookTickStat(arg0,arg1);
  }
  virtual MTAPIRES HookTickStat(int const arg0,MTTickStat &arg1);
  void _swig_upcall_OnTickServer(int const arg0,MTTick const &arg1) {
    IMTTickSink::OnTick(arg0,arg1);
  }
  virtual void OnTick(int const arg0,MTTick const &arg1);
  void _swig_upcall_OnTickStatServer(int const arg0,MTTickStat const &arg1) {
    IMTTickSink::OnTickStat(arg0,arg1);
  }
  virtual void OnTickStat(int const arg0,MTTickStat const &arg1);
 private:
  intgo go_val;
  Swig_memory *swig_mem;
};

#endif
